-- CreateTable
CREATE TABLE "USUARIO" (
    "ID_USUARIO" SERIAL NOT NULL,
    "NOMBRES" VARCHAR(100) NOT NULL,
    "APELLIDO_PATERNO" VARCHAR(50) NOT NULL,
    "APELLIDO_MATERNO" VARCHAR(50) NOT NULL,
    "ID_TIPO_USUARIO" INTEGER NOT NULL,
    "CORREO_ELECTRONICO" VARCHAR(100) NOT NULL,
    "ID_TIPO_DOCUMENTO" INTEGER NOT NULL,
    "TELEFONO" VARCHAR(12),
    "CONTRASENA" VARCHAR(100) NOT NULL,
    "FECHA_NACIMIENTO" DATE,
    "DIRECCION" VARCHAR(200),
    "GENERO" CHAR(1),
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "TIPO_USUARIO" (
    "ID_TIPO_USUARIO" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(50) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "TIPO_USUARIO_pkey" PRIMARY KEY ("ID_TIPO_USUARIO")
);

-- CreateTable
CREATE TABLE "TIPO_DOCUMENTO" (
    "ID_TIPO_DOCUMENTO" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(30) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "TIPO_DOCUMENTO_pkey" PRIMARY KEY ("ID_TIPO_DOCUMENTO")
);

-- CreateTable
CREATE TABLE "PONENTE" (
    "ID_PONENTE" SERIAL NOT NULL,
    "ID_TIPO_DOCUMENTO" INTEGER NOT NULL,
    "DOCUMENTO" VARCHAR(50) NOT NULL,
    "NOMBRES" VARCHAR(100) NOT NULL,
    "APELLIDOS" VARCHAR(100) NOT NULL,
    "ENTIDAD" VARCHAR(100) NOT NULL,
    "BIOGRAFIA" TEXT,
    "EMAIL" VARCHAR(100),
    "TELEFONO" VARCHAR(12),
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "PONENTE_pkey" PRIMARY KEY ("ID_PONENTE")
);

-- CreateTable
CREATE TABLE "UBICACION" (
    "ID_UBICACION" SERIAL NOT NULL,
    "DESCRIPCION" VARCHAR(100) NOT NULL,
    "DIRECCION" VARCHAR(200),
    "CAPACIDAD" INTEGER,
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "UBICACION_pkey" PRIMARY KEY ("ID_UBICACION")
);

-- CreateTable
CREATE TABLE "EVENTO" (
    "ID_EVENTO" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(255) NOT NULL,
    "ID_PONENTE" INTEGER NOT NULL,
    "ID_UBICACION" INTEGER NOT NULL,
    "ID_HORARIO" INTEGER NOT NULL,
    "DESCRIPCION" TEXT,
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "EVENTO_pkey" PRIMARY KEY ("ID_EVENTO")
);

-- CreateTable
CREATE TABLE "EVENTOS_ASISTIDOS" (
    "ID_EVENTO_ASISTIDO" SERIAL NOT NULL,
    "ID_EVENTO" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,
    "FECHA_ASISTENCIA" DATE,
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "EVENTOS_ASISTIDOS_pkey" PRIMARY KEY ("ID_EVENTO_ASISTIDO")
);

-- CreateTable
CREATE TABLE "HORARIO" (
    "ID_HORARIO" SERIAL NOT NULL,
    "HORA_INICIO" TIME(6) NOT NULL,
    "HORA_FIN" TIME(6) NOT NULL,
    "FECHA" DATE,
    "CREATED_AT" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(6),

    CONSTRAINT "HORARIO_pkey" PRIMARY KEY ("ID_HORARIO")
);

-- CreateTable
CREATE TABLE "MENSAJE" (
    "ID_MENSAJE" SERIAL NOT NULL,
    "CONTENIDO" VARCHAR(500) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_ROOM" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,

    CONSTRAINT "MENSAJE_pkey" PRIMARY KEY ("ID_MENSAJE")
);

-- CreateTable
CREATE TABLE "ROOM" (
    "ID_ROOM" SERIAL NOT NULL,
    "NOMBRE" VARCHAR(255) NOT NULL,

    CONSTRAINT "ROOM_pkey" PRIMARY KEY ("ID_ROOM")
);

-- CreateIndex
CREATE UNIQUE INDEX "USUARIO_CORREO_ELECTRONICO_key" ON "USUARIO"("CORREO_ELECTRONICO");

-- AddForeignKey
ALTER TABLE "USUARIO" ADD CONSTRAINT "USUARIO_ID_TIPO_USUARIO_fkey" FOREIGN KEY ("ID_TIPO_USUARIO") REFERENCES "TIPO_USUARIO"("ID_TIPO_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USUARIO" ADD CONSTRAINT "USUARIO_ID_TIPO_DOCUMENTO_fkey" FOREIGN KEY ("ID_TIPO_DOCUMENTO") REFERENCES "TIPO_DOCUMENTO"("ID_TIPO_DOCUMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PONENTE" ADD CONSTRAINT "PONENTE_ID_TIPO_DOCUMENTO_fkey" FOREIGN KEY ("ID_TIPO_DOCUMENTO") REFERENCES "TIPO_DOCUMENTO"("ID_TIPO_DOCUMENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTO" ADD CONSTRAINT "EVENTO_ID_PONENTE_fkey" FOREIGN KEY ("ID_PONENTE") REFERENCES "PONENTE"("ID_PONENTE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTO" ADD CONSTRAINT "EVENTO_ID_UBICACION_fkey" FOREIGN KEY ("ID_UBICACION") REFERENCES "UBICACION"("ID_UBICACION") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTO" ADD CONSTRAINT "EVENTO_ID_HORARIO_fkey" FOREIGN KEY ("ID_HORARIO") REFERENCES "HORARIO"("ID_HORARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS_ASISTIDOS" ADD CONSTRAINT "EVENTOS_ASISTIDOS_ID_EVENTO_fkey" FOREIGN KEY ("ID_EVENTO") REFERENCES "EVENTO"("ID_EVENTO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EVENTOS_ASISTIDOS" ADD CONSTRAINT "EVENTOS_ASISTIDOS_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MENSAJE" ADD CONSTRAINT "MENSAJE_ID_ROOM_fkey" FOREIGN KEY ("ID_ROOM") REFERENCES "ROOM"("ID_ROOM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MENSAJE" ADD CONSTRAINT "MENSAJE_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;
